// script.js - Translations and Render

const translations = {
  en: {
    subtitle: "What should we watch tonight?",
    movies: "Movies",
    tvShows: "TV Shows",
    searchPlaceholder: "Search...",
    settings: "Settings",
    contentLanguage: "Content Language",
    watchList: "Watchlist",
    watchedList: "Watched",
    changeCountry: "Change Country",
    decade: "Decade",
    allDecades: "All Decades",
    minRating: "Min Rating",
    duration: "Duration",
    ageRating: "Age Rating",
    any: "Any",
    showFilters: "More Filters",
    advancedFilters: "Advanced Filters",
    includeGenre: "Include Genres",
    excludeGenre: "Exclude Genres",
    platform: "Platforms",
    platformSearchPlaceholder: "Search platforms...",
    clearFilters: "Clear",
    applyFilters: "Apply",
    surpriseMe: "Surprise Me!",
    searching: "Searching...",
    noMoviesFound: "No movies found with these filters.",
    clearAllFilters: "Clear All Filters",
    welcomeMessage: "Click 'Surprise Me!' to discover your next watch.",
    cardYear: "Year",
    cardDuration: "Duration",
    cardSeasons: "Seasons",
    cardRating: "Rating",
    cardGenres: "Genres",
    cardDirector: "Director",
    cardAvailableOn: "Available on",
    cardAvailableToRent: "Available to Rent/Buy",
    cardCast: "Cast",
    cardCastNotFound: "Cast not available",
    cardStreamingNotFound: "Not available for streaming",
    cardTrailer: "Watch Trailer",
    cardSimilarMovies: "Similar Titles",
    cardMarkAsWatched: "Mark as Watched",
    cardIsWatched: "Watched",
    saveForLater: "Watchlist",
    shareButton: "Share",
    shareSuccess: "Link copied!",
    selectRegionPrompt: "Select Your Region",
    region: "Region",
    unwatch: "Remove",
    removeFromList: "Remove",
    installApp: "Install App",
    installInstructions: "Tap Share then 'Add to Home Screen' to install",
    cookieMessage: "We use local storage to save your preferences and watchlist.",
    cookieAccept: "Accept",
    details: "Details",
    toastWatched: "Marked as watched! ✓",
    toastUnwatched: "Removed from watched",
    toastAddedToWatchlist: "Added to watchlist! ♡",
    toastRemovedFromWatchlist: "Removed from watchlist"
  },
  es: {
    subtitle: "¿Qué deberíamos ver esta noche?",
    movies: "Películas",
    tvShows: "Series",
    searchPlaceholder: "Buscar...",
    settings: "Ajustes",
    contentLanguage: "Idioma del Contenido",
    watchList: "Mi Lista",
    watchedList: "Vistos",
    changeCountry: "Cambiar País",
    decade: "Década",
    allDecades: "Todas",
    minRating: "Puntuación Mín",
    duration: "Duración",
    ageRating: "Clasificación",
    any: "Cualquiera",
    showFilters: "Más Filtros",
    advancedFilters: "Filtros Avanzados",
    includeGenre: "Incluir Géneros",
    excludeGenre: "Excluir Géneros",
    platform: "Plataformas",
    platformSearchPlaceholder: "Buscar plataformas...",
    clearFilters: "Limpiar",
    applyFilters: "Aplicar",
    surpriseMe: "¡Sorpréndeme!",
    searching: "Buscando...",
    noMoviesFound: "No se encontraron películas con estos filtros.",
    clearAllFilters: "Limpiar Filtros",
    welcomeMessage: "¡Haz clic en 'Sorpréndeme!' para descubrir qué ver.",
    cardYear: "Año",
    cardDuration: "Duración",
    cardSeasons: "Temporadas",
    cardRating: "Puntuación",
    cardGenres: "Géneros",
    cardDirector: "Director",
    cardAvailableOn: "Disponible en",
    cardAvailableToRent: "Disponible para Alquilar/Comprar",
    cardCast: "Reparto",
    cardCastNotFound: "Reparto no disponible",
    cardStreamingNotFound: "No disponible en streaming",
    cardTrailer: "Ver Tráiler",
    cardSimilarMovies: "Títulos Similares",
    cardMarkAsWatched: "Marcar como Visto",
    cardIsWatched: "Visto",
    saveForLater: "Mi Lista",
    shareButton: "Compartir",
    shareSuccess: "¡Enlace copiado!",
    selectRegionPrompt: "Selecciona Tu Región",
    region: "Región",
    unwatch: "Quitar",
    removeFromList: "Quitar",
    installApp: "Instalar App",
    installInstructions: "Toca Compartir y luego 'Añadir a Inicio' para instalar",
    cookieMessage: "Usamos almacenamiento local para guardar tus preferencias y listas.",
    cookieAccept: "Aceptar",
    details: "Detalles",
    toastWatched: "¡Marcado como visto! ✓",
    toastUnwatched: "Eliminado de vistos",
    toastAddedToWatchlist: "¡Añadido a la lista! ♡",
    toastRemovedFromWatchlist: "Eliminado de la lista"
  }
};

// Render the app
ReactDOM.render(<AppWithProviders />, document.getElementById('root')); 