// script.js - Translations and Render

const translations = {
  en: {
    subtitle: "What should we watch tonight?",
    movies: "Movies",
    tvShows: "TV Shows",
    searchPlaceholder: "Search...",
    settings: "Settings",
    contentLanguage: "Content Language",
    siteLanguage: "Site Language",
    watchList: "Watchlist",
    watchedList: "Watched",
    changeCountry: "Change Country",
    decade: "Decade",
    allDecades: "All Decades",
    minRating: "Min Rating",
    duration: "Duration",
    ageRating: "Age Rating",
    any: "Any",
    showFilters: "More Filters",
    advancedFilters: "Advanced Filters",
    includeGenre: "Include Genres",
    excludeGenre: "Exclude Genres",
    platform: "Platforms",
    platformSearchPlaceholder: "Search platforms...",
    clearFilters: "Clear",
    applyFilters: "Apply",
    surpriseMe: "Surprise Me!",
    searching: "Searching...",
    noMoviesFound: "No movies found with these filters.",
    clearAllFilters: "Clear All Filters",
    welcomeMessage: "Click 'Surprise Me!' to discover your next watch.",
    cardYear: "Year",
    cardDuration: "Duration",
    cardSeasons: "Seasons",
    cardRating: "Rating",
    cardGenres: "Genres",
    cardDirector: "Director",
    cardAvailableOn: "Available on",
    cardAvailableToRent: "Available to Rent/Buy",
    cardCast: "Cast",
    cardCastNotFound: "Cast not available",
    cardStreamingNotFound: "Not available for streaming",
    cardTrailer: "Watch Trailer",
    cardSimilarMovies: "Similar Titles",
    cardMarkAsWatched: "Mark as Watched",
    cardIsWatched: "Watched",
    saveForLater: "Watchlist",
    shareButton: "Share",
    shareSuccess: "Link copied!",
    selectRegionPrompt: "Select Your Region",
    selectRegionSubtitle: "We'll show you what's available to stream in your country.",
    selectRegionHint: "Your choice is saved locally and can be changed anytime in Settings.",
    region: "Region",
    unwatch: "Remove",
    removeFromList: "Remove",
    installApp: "Install App",
    installInstructions: "Tap Share then 'Add to Home Screen' to install",
    cookieMessage: "We use local storage to save your preferences and watchlist.",
    cookieAccept: "Accept",
    details: "Details",
    toastWatched: "Marked as watched! ✓",
    toastUnwatched: "Removed from watched",
    toastAddedToWatchlist: "Added to watchlist! ♡",
    toastRemovedFromWatchlist: "Removed from watchlist",
    done: "Done",
    watchedEmpty: "No watched titles yet",
    watchedEmptyHint: "Mark titles as watched and they'll appear here",
    watchlistEmpty: "Your watchlist is empty",
    watchlistEmptyHint: "Save titles to watch later and they'll appear here",
    knownFor: "Known For",
    noBiography: "No biography available.",
    noNotableWorks: "No notable works found.",
    filterByPerson: "Filter by person",
    whatRole: "What role did they have?",
    roleActor: "Actor",
    roleActorDesc: "Appeared on screen",
    roleDirector: "Director",
    roleDirectorDesc: "Directed the film",
    roleWriter: "Writer",
    roleWriterDesc: "Wrote the screenplay",
    roleProducer: "Producer",
    roleProducerDesc: "Produced the project",
    cancel: "Cancel",
    oneMoreThing: "One more thing",
    whichLanguage: "Which language do you prefer?",
    skip: "Skip",
    titles: "title",
    titlesPlural: "titles",
    activeFilter: "active filter",
    activeFilters: "active filters",
    readMore: "Read more",
    readLess: "Show less",
    cardDirectorLabel: "Directed by",
    shareTitle: "Share this title",
    shareWhatsApp: "WhatsApp",
    shareTelegram: "Telegram",
    shareEmail: "Email",
    shareCopyLink: "Copy Link",
    shareLinkCopied: "Link copied!",
    seasons: "Seasons",
episodes: "ep",
seasonFilter: "Seasons",
anySeasons: "Any",
seasonsList: "Season breakdown",
findInCinemas: "Find in cinemas near you",
inCinemasNow: "In cinemas now",
  },


  es: {
    subtitle: "¿Qué deberíamos ver esta noche?",
    movies: "Películas",
    tvShows: "Series",
    searchPlaceholder: "Buscar...",
    settings: "Ajustes",
    contentLanguage: "Idioma del Contenido",
    siteLanguage: "Idioma del Sitio",
    watchList: "Mi Lista",
    watchedList: "Vistos",
    changeCountry: "Cambiar País",
    decade: "Década",
    allDecades: "Todas",
    minRating: "Puntuación Mín",
    duration: "Duración",
    ageRating: "Clasificación",
    any: "Cualquiera",
    showFilters: "Más Filtros",
    advancedFilters: "Filtros Avanzados",
    includeGenre: "Incluir Géneros",
    excludeGenre: "Excluir Géneros",
    platform: "Plataformas",
    platformSearchPlaceholder: "Buscar plataformas...",
    clearFilters: "Limpiar",
    applyFilters: "Aplicar",
    surpriseMe: "¡Sorpréndeme!",
    searching: "Buscando...",
    noMoviesFound: "No se encontraron películas con estos filtros.",
    clearAllFilters: "Limpiar Filtros",
    welcomeMessage: "¡Haz clic en 'Sorpréndeme!' para descubrir qué ver.",
    cardYear: "Año",
    cardDuration: "Duración",
    cardSeasons: "Temporadas",
    cardRating: "Puntuación",
    cardGenres: "Géneros",
    cardDirector: "Director",
    cardAvailableOn: "Disponible en",
    cardAvailableToRent: "Disponible para Alquilar/Comprar",
    cardCast: "Reparto",
    cardCastNotFound: "Reparto no disponible",
    cardStreamingNotFound: "No disponible en streaming",
    cardTrailer: "Ver Tráiler",
    cardSimilarMovies: "Títulos Similares",
    cardMarkAsWatched: "Marcar como Visto",
    cardIsWatched: "Visto",
    saveForLater: "Mi Lista",
    shareButton: "Compartir",
    shareSuccess: "¡Enlace copiado!",
    selectRegionPrompt: "Selecciona Tu Región",
    selectRegionSubtitle: "Te mostraremos qué hay disponible en tu país.",
    selectRegionHint: "Tu elección se guarda localmente y puedes cambiarla en Ajustes.",
    region: "Región",
    unwatch: "Quitar",
    removeFromList: "Quitar",
    installApp: "Instalar App",
    installInstructions: "Toca Compartir y luego 'Añadir a Inicio' para instalar",
    cookieMessage: "Usamos almacenamiento local para guardar tus preferencias y listas.",
    cookieAccept: "Aceptar",
    details: "Detalles",
    toastWatched: "¡Marcado como visto! ✓",
    toastUnwatched: "Eliminado de vistos",
    toastAddedToWatchlist: "¡Añadido a la lista! ♡",
    toastRemovedFromWatchlist: "Eliminado de la lista",
    done: "Hecho",
    watchedEmpty: "Aún no hay títulos vistos",
    watchedEmptyHint: "Marca títulos como vistos y aparecerán aquí",
    watchlistEmpty: "Tu lista está vacía",
    watchlistEmptyHint: "Guarda títulos para ver más tarde y aparecerán aquí",
    knownFor: "Conocido Por",
    noBiography: "Biografía no disponible.",
    noNotableWorks: "No se encontraron obras destacadas.",
    filterByPerson: "Filtrar por persona",
    whatRole: "¿Qué rol tuvo?",
    roleActor: "Actor",
    roleActorDesc: "Apareció en pantalla",
    roleDirector: "Director",
    roleDirectorDesc: "Dirigió la película",
    roleWriter: "Guionista",
    roleWriterDesc: "Escribió el guión",
    roleProducer: "Productor",
    roleProducerDesc: "Produjo el proyecto",
    cancel: "Cancelar",
    oneMoreThing: "Una cosa más",
    whichLanguage: "¿Qué idioma prefieres?",
    skip: "Omitir",
    titles: "título",
    titlesPlural: "títulos",
    activeFilter: "filtro activo",
    activeFilters: "filtros activos",
    readMore: "Leer más",
    readLess: "Mostrar menos",
    cardDirectorLabel: "Dirigido por",
    shareTitle: "Compartir este título",
    shareWhatsApp: "WhatsApp",
    shareTelegram: "Telegram",
    shareEmail: "Email",
    shareCopyLink: "Copiar enlace",
    shareLinkCopied: "¡Enlace copiado!",
    seasons: "Temporadas",
episodes: "ep",
seasonFilter: "Temporadas",
anySeasons: "Cualquiera",
seasonsList: "Desglose por temporada",
findInCinemas: "Buscar cines cercanos",
inCinemasNow: "En cines ahora",
  }
};

// Render the app
ReactDOM.render(<AppWithProviders />, document.getElementById('root')); 